version: '3'

networks:
  consul-network:
    driver: bridge

services:
  consul-node1:
    image: bloque/consul-envoy
    networks:
      - consul-network
    environment:
      - SERVICE_NAME=echo-service
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_DATACENTER=dc1
      - CONSUL_LOCAL_CONFIG={"primary_datacenter":"dc1","ports":{"grpc":8502},"connect":{"enabled":true},"enable_central_service_config":true,"node_name":"consul-node1"}
    ports:
      - '5678:5678'
      - '8300:8300'
      - '8301:8301'
      - '8301:8301/udp'
      - '8500:8500'
      - '8600:8600'
      - '8600:8600/udp'
    volumes:
      - 'consul-node1_data:/bitnami'
#      - './dc1-conf:/opt/bitnami/consul/conf'

  consul-node2:
    image: bloque/consul-envoy
    networks:
      - consul-network
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
      - CONSUL_DATACENTER=dc1
      - CONSUL_LOCAL_CONFIG={"primary_datacenter":"dc1","ports":{"grpc":8502},"connect":{"enabled":true},"enable_central_service_config":true,"node_name":"consul-node2"}
    volumes:
      - 'consul-node2_data:/bitnami'

  consul-node3:
    image: bloque/consul-envoy
    networks:
      - consul-network
    environment:
      - CONSUL_BOOTSTRAP_EXPECT=3
      - CONSUL_CLIENT_LAN_ADDRESS=0.0.0.0
      - CONSUL_DISABLE_KEYRING_FILE=true
      - CONSUL_RETRY_JOIN_ADDRESS=consul-node1
      - CONSUL_ENABLE_UI=false
      - CONSUL_DATACENTER=dc1
      - CONSUL_LOCAL_CONFIG={"primary_datacenter":"dc1","ports":{"grpc":8502},"connect":{"enabled":true},"enable_central_service_config":true,"node_name":"consul-node3"}
    volumes:
      - 'consul-node3_data:/bitnami'

volumes:
  consul-node1_data:
    driver: local
  consul-node2_data:
    driver: local
  consul-node3_data:
    driver: local